;FINALMENTE Y COMO NUNCA: 
;CON USTEDES: EEEEEEEL CODIGO
;CHA CHAN CHA CHANNN
;ESTE ESEN EL Q SERIE Y MOTOR FUNCO PERO LA CONVERSION ESTA RAARA: ; Este es motor con serie y pote a adc display con orientacion hacia adresl (ignora los dos MSB)
LIST P=16F887
RADIX DEC
#include "p16f887.inc"

;--------------------------------------------------------
; CONFIG
;--------------------------------------------------------
__CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
__CONFIG _CONFIG2, _WRT_OFF & _BOR4V_BOR40V


PASOS   	EQU 0x70
W_TEMP  	EQU 0x71
STATUS_TEMP EQU 0x72
D1      	EQU 0x73
D2      	EQU 0x74
DISP    	EQU 0x75
NIB_BAJO	EQU 0x76
NIB_ALTO	EQU 0x77
DOSIS   	EQU 0x78
PASOS_H EQU 0X79
contador147 equ 0x7A
contador10 EQU 0x7B
 
 
 
ORG 0x00
GOTO INICIO
 
ORG 0x04
GOTO ISR
 
INICIO  
 
;BANCO 0
CLRF PORTD
CLRF PORTB
CLRF PORTC
CLRF PASOS
CLRF PASOS_H
CLRF DISP
CLRF DOSIS
CLRF contador147
CLRF contador10
MOVLW B'10000001'
MOVWF ADCON0
MOVLW B'10010000'
MOVWF RCSTA
    
;BANCO 1    
BSF STATUS, RP0
MOVLW B'00000001'
MOVWF TRISB   
MOVLW B'10000111'
MOVWF OPTION_REG
CLRF TRISD
MOVLW B'10000000'
MOVWF ADCON1
MOVLW B'10000000'
MOVWF TRISC
MOVLW B'00100100'
MOVWF TXSTA
MOVLW .25
MOVWF SPBRG
BSF PIE1, RCIE

 
;BANCO 3
BSF STATUS, RP1
MOVLW B'00000001'
MOVWF ANSEL
CLRF ANSELH
BCF BAUDCTL, BRG16
  	 
;BANCO 0
BCF STATUS, RP0
BCF STATUS, RP1
MOVLW B'11110000'
BCF PIR1, RCIF
MOVWF INTCON
CLRF PORTB
MOVLW .237
MOVWF TMR0
BCF PORTB,7
BCF INTCON, INTF
BCF INTCON, T0IF

LOOP
GOTO LOOP
 
ISR
MOVWF W_TEMP
SWAPF STATUS, W
MOVWF STATUS_TEMP

BTFSC PIR1, RCIF
GOTO PERIF
BTFSC INTCON,T0IF
goto TIMER0
goto PULSADOR


PERIF
BTFSS RCSTA, OERR
GOTO LEER_UART
BCF RCSTA, CREN
BSF RCSTA, CREN

LEER_UART
MOVF RCREG, W
MOVWF DOSIS
MOVLW 0x30
SUBWF DOSIS, W
BTFSS STATUS, C
GOTO FIN_PERIF
MOVLW 0X3A
SUBWF DOSIS, W
BTFSC STATUS, C
GOTO FIN_PERIF
MOVLW 0X30
SUBWF DOSIS, F

; DOSIS ya vale de 0 a 9

MOVF DOSIS, W

   	; byte alto

CALL MOVER_PASOS

CALL ACTUALIZAR_ADC
GOTO FIN_PERIF

 ;====================================================
; MOVER_PASOS
; Mueve el motor PASOS_H:PASOS veces
;====================================================

MOVER_PASOS
    MOVLW   .147
    MOVWF   contador147

BUCLE_147
    CALL    DAR_PASO
    DECFSZ  contador147, F
    GOTO    BUCLE_147

    DECFSZ  DOSIS, F
    GOTO    MOVER_PASOS

    RETURN


 
DAR_PASO
BSF 	PORTB, 6     	 
CALL	DELAY_STEP
BCF 	PORTB, 6     	 
CALL	DELAY_STEP
RETURN

DELAY_STEP
MOVLW   D'40'
MOVWF   D1
DLY1
MOVLW   D'200'
MOVWF   D2
DLY2
DECFSZ  D2, F
GOTO	DLY2
DECFSZ  D1, F
GOTO	DLY1
RETURN
  	 
FIN_PERIF
BCF PIR1, RCIF
GOTO FIN_ISR
	 
ACTUALIZAR_ADC
CALL DELAY_STEP
BSF ADCON0, 1
CALL DELAY_ADC
BSF STATUS, RP0
MOVF ADRESL, W
ANDLW 0x0F
MOVWF NIB_BAJO
MOVF ADRESL, W
ANDLW 0xF0
MOVWF NIB_ALTO
SWAPF NIB_ALTO, F
BCF STATUS, RP0
RETURN

DELAY_ADC
BTFSC   ADCON0, 1
GOTO	DELAY_ADC
RETURN
  	 


TIMER0
MOVLW .237
MOVWF TMR0
CLRF PORTD
BCF PORTB, 4
BCF PORTB, 5

BTFSS DISP, 0
GOTO PRIMERO
GOTO SEGUNDO

SEGUNDO
MOVF NIB_ALTO, W
CALL TABLA
MOVWF PORTD
BSF PORTB,4
BCF DISP, 0
BCF INTCON, T0IF
GOTO FIN_ISR

PRIMERO
MOVF NIB_BAJO, W
CALL TABLA
MOVWF PORTD
BSF PORTB,5
BSF DISP, 0
BCF INTCON, T0IF
GOTO FIN_ISR

    
PULSADOR
BSF PORTB,7
movlw .10
movwf contador10
BUCLEREPETIR10
CALL MOVER1ML
DECFSZ contador10
goto BUCLEREPETIR10

CALL ACTUALIZAR_ADC
BCF INTCON, INTF
GOTO FIN_ISR

MOVER1ML
MOVLW .147
MOVWF PASOS
BUCLE_20

    	CALL	DAR_PASO

    	DECFSZ  PASOS, F
    	GOTO	BUCLE_20
RETURN

FIN_ISR
BCF PORTB,7
SWAPF STATUS_TEMP, W
MOVWF STATUS
SWAPF W_TEMP, F
SWAPF W_TEMP, W
RETFIE






TABLA
   ADDWF   PCL, F

    	RETLW   B'00111111'   	; 0
    	RETLW   B'00000110'   	; 1
    	RETLW   B'01011011'   	; 2
    	RETLW   B'01001111'   	; 3
    	RETLW   B'01100110'   	; 4
    	RETLW   B'01101101'   	; 5
    	RETLW   B'01111101'   	; 6
    	RETLW   B'00000111'   	; 7
    	RETLW   B'01111111'   	; 8
    	RETLW   B'01101111'   	; 9
    	RETLW   B'01110111'   	; A
    	RETLW   B'01111100'   	; b
    	RETLW   B'00111001'   	; C
    	RETLW   B'01011110'   	; d
    	RETLW   B'01111001'   	; E
    	RETLW   B'01110001'   	; F

END